name: MetricsUpdater

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      -  uses: stalomeow/metrics@projects-v2
         with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: github-metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Paris
          optimize: svg
          
          plugin_lines: yes

          plugin_languages: yes
          plugin_languages_ignored: html, css, cmake, hack, jupyter notebook
          plugin_languages_colors: github
          plugin_languages_details: bytes-size, percentage

          plugin_isocalendar: yes

          plugin_traffic: yes

          plugin_achievements: yes
          plugin_achievements_secrets: yes
          plugin_achievements_display: compact
          plugin_achievements_limit: 0

          plugin_repositories_affiliations : ""
          plugin_commits: yes
          plugin_commits_private: yes 